App\Auth\Infraestructure\Symfony\Controller\AuthController:
    resource: App\Auth\Infraestructure\Symfony\Controller\AuthController
    type: attribute

App\Auth\Infraestructure\Symfony\Controller\UserController:
    resource: App\Auth\Infraestructure\Symfony\Controller\UserController
    type: attribute

App\Home\Infraestructure\Symfony\Controller\MeasurementController:
    resource: App\Home\Infraestructure\Symfony\Controller\MeasurementController
    type: attribute        
